# Generated by Django 4.2.3 on 2023-08-15 15:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('oneday', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Hashtag',
            new_name='OnedayHashtag',
        ),
        migrations.RenameModel(
            old_name='Review',
            new_name='OnedayReview',
        ),
        migrations.AlterField(
            model_name='onedaycreate',
            name='period1',
            field=models.DateField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='onedaycreate',
            name='period2',
            field=models.DateField(default='', max_length=50),
        ),
    ]
