# Generated by Django 4.2.3 on 2023-08-12 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oneday', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnedayCreate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('craft', models.BooleanField(default=False)),
                ('cook', models.BooleanField(default=False)),
                ('art', models.BooleanField(default=False)),
                ('activity', models.BooleanField(default=False)),
                ('sports', models.BooleanField(default=False)),
                ('music', models.BooleanField(default=False)),
                ('etc', models.BooleanField(default=False)),
                ('number', models.CharField(max_length=50)),
                ('period', models.CharField(max_length=50)),
                ('region', models.CharField(default='', max_length=50)),
                ('hashtag', models.CharField(default='', max_length=50)),
                ('title', models.CharField(default='', max_length=50)),
                ('content', models.CharField(default='', max_length=50)),
                ('picture', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='OnedayRecruit',
        ),
    ]
