# Generated by Django 4.2.3 on 2023-08-15 17:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('oneday', '0002_rename_hashtag_onedayhashtag_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='onedaycomment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='oneday.onedaycomment'),
        ),
        migrations.AlterField(
            model_name='onedayreview',
            name='oneday',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='OnedayReviews', to='oneday.onedaycreate'),
        ),
        migrations.AlterField(
            model_name='onedayreview',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='OnedayReviews', to=settings.AUTH_USER_MODEL),
        ),
    ]
