# Generated by Django 4.2.3 on 2023-08-12 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oneday', '0002_onedaycreate_delete_onedayrecruit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onedaycreate',
            name='activity',
        ),
        migrations.RemoveField(
            model_name='onedaycreate',
            name='art',
        ),
        migrations.RemoveField(
            model_name='onedaycreate',
            name='cook',
        ),
        migrations.RemoveField(
            model_name='onedaycreate',
            name='craft',
        ),
        migrations.RemoveField(
            model_name='onedaycreate',
            name='etc',
        ),
        migrations.RemoveField(
            model_name='onedaycreate',
            name='music',
        ),
        migrations.RemoveField(
            model_name='onedaycreate',
            name='sports',
        ),
        migrations.AddField(
            model_name='onedaycreate',
            name='category',
            field=models.CharField(choices=[('craft', '공예'), ('cook', '요리'), ('art', '미술'), ('activity', '액티비티'), ('sports', '운동'), ('music', '음악'), ('etc', '기타')], default='etc', max_length=50, verbose_name='모집 분야'),
        ),
        migrations.AlterField(
            model_name='onedaycreate',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
