# Generated by Django 4.2.3 on 2023-08-12 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oneday', '0003_remove_onedaycreate_activity_remove_onedaycreate_art_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='onedaycreate',
            name='status',
            field=models.CharField(choices=[('teacher', '선생님입니다'), ('student', '배우미입니다')], default='student', max_length=20),
        ),
    ]
