# Generated by Django 4.2.3 on 2023-08-16 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oneday', '0003_onedaycomment_parent_alter_onedayreview_oneday_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onedaycomment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='OnedayComments', to='oneday.onedaycomment'),
        ),
    ]
