# Generated by Django 4.2.3 on 2023-08-12 12:25

from django.db import migrations
import django_summernote.fields


class Migration(migrations.Migration):

    dependencies = [
        ('oneday', '0004_onedaycreate_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onedayapply',
            name='memo',
            field=django_summernote.fields.SummernoteTextField(),
        ),
        migrations.AlterField(
            model_name='onedaycreate',
            name='content',
            field=django_summernote.fields.SummernoteTextField(),
        ),
    ]
