# Generated by Django 4.2.3 on 2023-08-17 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oneday', '0004_alter_onedaycomment_parent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='onedayapply',
            old_name='phone',
            new_name='phone1',
        ),
        migrations.AddField(
            model_name='onedayapply',
            name='phone2',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='onedayapply',
            name='phone3',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
