# Generated by Django 4.2.3 on 2023-08-13 01:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from datetime import date


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('oneday', '0006_remove_onedaycreate_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='OnedayApply',
        ),
        migrations.RemoveField(
            model_name='onedaycreate',
            name='category',
        ),
        migrations.RemoveField(
            model_name='onedaycreate',
            name='hashtag',
        ),
        migrations.RemoveField(
            model_name='onedaycreate',
            name='period',
        ),
        migrations.RemoveField(
            model_name='onedaycreate',
            name='picture',
        ),
        migrations.AddField(
            model_name='onedaycreate',
            name='field',
            field=models.CharField(choices=[('휴대전화', '휴대전화'), ('인터넷', '인터넷'), ('키오스크', '키오스크'), ('생활편의', '생활편의'), ('기타', '기타')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='onedaycreate',
            name='period1',
            field=models.DateField(default=date(2023, 8, 10)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='onedaycreate',
            name='period2',
            field=models.DateField(default=date(2023, 8, 15)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='onedaycreate',
            name='photo',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='onedaycreate',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='onedaycreate',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='onedaycreate',
            name='number',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='onedaycreate',
            name='title',
            field=models.CharField(max_length=50),
        ),
        migrations.AddField(
            model_name='comment',
            name='oneday',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oneday.onedaycreate'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
