# Generated by Django 4.2.3 on 2023-08-13 01:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oneday', '0008_alter_onedaycreate_period1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onedaycreate',
            name='period1',
            field=models.DateField(default=datetime.date(2023, 8, 10)),
        ),
        migrations.AlterField(
            model_name='onedaycreate',
            name='period2',
            field=models.DateField(default=datetime.date(2023, 8, 15)),
        ),
    ]
