# Generated by Django 4.2.3 on 2023-08-13 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oneday', '0009_alter_onedaycreate_period1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onedaycreate',
            name='field',
            field=models.CharField(choices=[('공예', '공예'), ('요리', '요리'), ('미술', '미술'), ('액티비티', '운동'), ('음악', '음악'), ('기타', '기타')], default='', max_length=20),
        ),
    ]
