# Generated by Django 4.2.3 on 2023-08-13 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oneday', '0010_alter_onedaycreate_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='onedaycreate',
            name='hashtag',
            field=models.CharField(default='', max_length=50),
        ),
    ]
