# Generated by Django 4.2.3 on 2023-08-13 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oneday', '0012_onedayapply'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hashtag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='onedaycreate',
            name='hashtag',
        ),
        migrations.AddField(
            model_name='onedaycreate',
            name='hashtags',
            field=models.ManyToManyField(to='oneday.hashtag'),
        ),
    ]
